### ISSUE TITLE
homing with plate at the bottom.

### ISSUE THREAD

**Issue by corrado-c** [Darkwulf183/Tronxy-X5SA-Printer.cfg-and-more-for-Klipper#1]
Hello!
in my configuration the heavy plate is all at the bottom, when I do the first homing it obviously tries to go down a little before going up.

in marlin there was an uncomment line. here I don't know the solution. it can be done?

**Comment by Darkwulf183** [comment]
Why exactly are you opening an issue in my repo. I have only put my known profiles online and do not edit clipper issues on Github. For that I have my Youtube channel. Besides, that's what all the docs in Klipper are for, to be able to read out exactly that for yourself. I don't do anything else at this point. I'm closing the issue after this message. As this is not the place where I will answer such questions. But very briefly. Read this... Because it says that for every homing this Z offset is used. So you should set it to 0 or close to 0. However, I can't tell you exactly whether this is the solution, because I haven't tried anything like this with the table at the bottom.

[safe_z_home]
z_hop:
Distance (in mm) to lift the Z axis prior to homing. This is
applied to any homing command, even if it doesn't home the Z axis.
If the Z axis is already homed and the current Z position is less
than z_hop, then this will lift the head to a height of z_hop. If
the Z axis is not already homed the head is lifted by z_hop.
The default is to not implement Z hop.

**Comment by corrado-c** [comment]
ok ok!  do not panic! Hahahahaha  I just used a GitHub function!  I didn't come knocking on your door!  I hadn't read that it couldn't be done, I beg your pardon.

**Comment by Darkwulf183** [comment]
Hi you don't need to apologise. I just need to contain this directly. Because if I write 50 messages with you now. Then what happened at the very beginning will happen... The Youtube channel is almost dead because everyone only posts on Github and uses that as half of the forum. I don't want to have that again. Because then everyone asks directly without watching the video and I can't keep up with the writing. Hence the brash answer. Did you at least achieve what you wanted with what I wrote to you? You can get back to me if that worked.
